var liste = {

    noms: [
        "Michel Varuk",
        "Jim Carrey",
        "Emma Watson",
        "Renaud",
        "Jacques",
        "Bernadette",
        "Léa",
        "Nina",
        "Jacques",
        "Michel",
        "H.P Lovecraft",
        "Bill Gates",
        "Alert Einstein",
        "Vivala",
        "Eminem",
        "Paul Rudd",
        "Johnny Depp",
        "The Rock",
        "Julien Lepers",
        "Hugh Jackman",
        "Gotaga",
        "Philippe Etchebest"
    ],

    objets: [
        "ordinateur",
        "téléphone",
        "ordinateur",
        "dé à coudre",
        "clavier",
        "tasse",
        "sabre",
        "cuillière",
        "manette",
        "clavier",
        "ordinateur",
        "vélo",
        "téléphone portable",
        "montre",
        "décapsuleur",
        "ballon de foot",
        "pièces jaunes",
        "lunettes",
        "fourchette",
        "tasse",
        "avion",
        "miche de pain"
    ],

    temperatures: [
        10,
        30,
        -50,
        5,
        69,
        18,
        -30,
        -40,
        69,
        70,
        5,
        28,
        37,
        100,
        12,
        25,
        37,
        25,
        28,
        24,
        30,
        -5
    ],

    lieux: [
        "Floyon",
        "Wignehies",
        "Tokyo",
        "Reykjavik",
        "Le Touquet",
        "Fourmies",
        "Palais de l'Elysée",
        "Mairie de Paris",
        "Mc Do",
        "Burger King",
        "Chuttes du Niagara",
        "Hide Park",
        "Barcelona",
        "Paris",
        "Bondy",
        "Rio de Janeiro",
        "Big Ben",
        "Mont Fuji",
        "Mc Do",
        "KFC",
        "Paris",
        "Montcuq"
    ],

    verbes: [
        "coder",
        "copier",
        "nager",
        "monter",
        "développer",
        "jouer",
        "voter",
        "anarquer",
        "jouer",
        "manger",
        "accomplir",
        "communiquer",
        "coder",
        "coordonner",
        "aimer",
        "être",
        "soulever",
        "évoluer",
        "jouer",
        "manger",
        "s'envoyer",
        "enfourner"
    ],

};